#!/bin/bash
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run -d \
       --privileged \
       --name ansible-builder \
       --rm \
       --volume "${MYDIR}/ansible-setup:/ansible-setup:ro" \
       --volume "${MYDIR}/container-out:/ansible-container:rw" \
       docker:dind

docker exec -it ansible-builder /bin/sh
