#!/bin/bash
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run \
       --privileged \
       --name ansible-builder \
       --rm \
       --volume "${MYDIR}/ansible-builder:/ansible-builder:ro" \
       docker:dind \
       /ansible-builder/build-image
