version: 3

images:
  base_image:
    name: maven:3.9.6-eclipse-temurin-11-alpine
options:
  package_manager_path: /usr/local/sbin/pm
additional_build_steps:
  prepend_base:
    - ENV PYTHONUNBUFFERED=1
    - RUN apk add --update --no-cache python3 py3-pip
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh
    - sshpass
  galaxy:
    collections:
    - name: community.docker
